name: todolist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2  
  flutter_local_notifications: ^19.0.0
  intl: ^0.20.2
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
